import { z } from 'zod';
import { createEndpoint, Locations } from 'zite-integrations-backend-sdk';

const SEED_DATA = [
  {
    name: 'Noisebridge',
    latitude: 37.7625,
    longitude: -122.4196,
    type: 'Makerspace' as const,
    capabilities: ['3D Printing', 'CNC', 'Laser Cutting', 'Electronics', 'PCB', 'Sewing'],
    membershipCost: 'Free (donate what you can)',
    sourceLink: 'https://www.noisebridge.net',
    notes: 'Community-run hackerspace. Do-ocracy. Open 24/7 for members.',
  },
  {
    name: 'SFPL Main Branch — Tech Lab',
    latitude: 37.7786,
    longitude: -122.4162,
    type: 'Library' as const,
    capabilities: ['3D Printing', 'Vinyl Cutting / Cricut', 'Electronics'],
    membershipCost: 'Free (SF library card required)',
    sourceLink: 'https://sfpl.org/locations/main-library',
    notes: 'Tech Lab on the 5th floor. Book equipment time online.',
  },
  {
    name: 'SFPL Eureka Valley Branch',
    latitude: 37.7633,
    longitude: -122.4326,
    type: 'Library' as const,
    capabilities: ['3D Printing', 'Vinyl Cutting / Cricut'],
    membershipCost: 'Free (SF library card required)',
    sourceLink: 'https://sfpl.org/locations/eureka-valley',
    notes: 'Harvey Milk Memorial Library. Maker Lab available.',
  },
  {
    name: 'SFPL Mission Branch',
    latitude: 37.7488,
    longitude: -122.4241,
    type: 'Library' as const,
    capabilities: ['3D Printing'],
    membershipCost: 'Free (SF library card required)',
    sourceLink: 'https://sfpl.org/locations/mission',
    notes: 'Drop-in maker hours available.',
  },
  {
    name: 'SFPL Portola Branch',
    latitude: 37.7244,
    longitude: -122.4066,
    type: 'Library' as const,
    capabilities: ['3D Printing', 'Vinyl Cutting / Cricut'],
    membershipCost: 'Free (SF library card required)',
    sourceLink: 'https://sfpl.org/locations/portola',
    notes: 'Makerspace sessions on weekends.',
  },
  {
    name: 'SFPL Anza Branch',
    latitude: 37.7729,
    longitude: -122.4986,
    type: 'Library' as const,
    capabilities: ['3D Printing'],
    membershipCost: 'Free (SF library card required)',
    sourceLink: 'https://sfpl.org/locations/anza',
    notes: 'Maker equipment available during open hours.',
  },
  {
    name: 'SFPL Chinatown / Him Mark Lai Branch',
    latitude: 37.7960,
    longitude: -122.4079,
    type: 'Library' as const,
    capabilities: ['3D Printing', 'Vinyl Cutting / Cricut'],
    membershipCost: 'Free (SF library card required)',
    sourceLink: 'https://sfpl.org/locations/chinatown',
    notes: 'Creative tech resources available.',
  },
  {
    name: 'Exploratorium Tinkering Studio',
    latitude: 37.8014,
    longitude: -122.3974,
    type: 'Makerspace' as const,
    capabilities: ['Electronics', 'Sewing', 'Woodworking'],
    membershipCost: 'Admission required (~$30 adult)',
    sourceLink: 'https://www.exploratorium.edu/tinkering',
    notes: 'World-class tinkering lab at Pier 15. Hands-on making for all ages.',
  },
  {
    name: 'Gray Area',
    latitude: 37.7517,
    longitude: -122.4186,
    type: 'Makerspace' as const,
    capabilities: ['Laser Cutting', 'Electronics', 'Vinyl Cutting / Cricut'],
    membershipCost: 'Membership from $75/month',
    sourceLink: 'https://grayarea.org',
    notes: 'Arts and technology nonprofit. Equipment access with membership.',
  },
  {
    name: 'SFPL Ocean View Branch',
    latitude: 37.7150,
    longitude: -122.4503,
    type: 'Library' as const,
    capabilities: ['3D Printing'],
    membershipCost: 'Free (SF library card required)',
    sourceLink: 'https://sfpl.org/locations/ocean-view',
    notes: 'Scheduled maker sessions available.',
  },
  {
    name: 'Recology Artist in Residence Studio',
    latitude: 37.7335,
    longitude: -122.3987,
    type: 'Makerspace' as const,
    capabilities: ['Woodworking', 'Sewing', 'Electronics'],
    membershipCost: 'Program-based access',
    sourceLink: 'https://www.recologysf.com/index.php/community/air',
    notes: 'Studio space adjacent to transfer station. Open studio events periodically.',
  },
  {
    name: 'SFPL Richmond Branch',
    latitude: 37.7797,
    longitude: -122.4631,
    type: 'Library' as const,
    capabilities: ['3D Printing', 'Vinyl Cutting / Cricut'],
    membershipCost: 'Free (SF library card required)',
    sourceLink: 'https://sfpl.org/locations/richmond',
    notes: 'Maker Lab with scheduled equipment sessions.',
  },
];

export default createEndpoint({
  description: 'Seeds the locations database (run once)',
  inputSchema: z.object({ secret: z.string() }),
  outputSchema: z.object({ inserted: z.number() }),
  execute: async ({ input }) => {
    if (input.secret !== 'seed-fabnetwork-2024') throw new Error('Unauthorized');
    await Locations.bulkCreate({ records: SEED_DATA });
    return { inserted: SEED_DATA.length };
  },
});
